### ISSUE TITLE
Suggestion of fix on Meta.php

### ISSUE THREAD

**Issue by jcabanillas** [Amirax/yii2-seo-tools#1]
Replace: 
$tags = ArrayHelper::merge(
            $this->_defaultMetaData['tags'],
            $data['tags']
        );
With:
$tags = ArrayHelper::merge(
            array_key_exists('tags', $this->_defaultMetaData) ? $this->_defaultMetaData['tags'] : [],
            $data['tags']
        );

**Comment by maxvoronov** [comment]
Hello @jcabanillas,
Your suggestion has been approved. Thank you.
